### DISCUSSION TITLE
Sunbird RC Installation & Use-case Setup Issue

### DISCUSSION THREAD

**Discussion by NageshRaykar** [Sunbird-RC/community#116] [Issues] [answered]
@dileepbapat @kesavanp123 @coolbung @parthlawate 
# <h1> Issue in sunbird RC Setup

We have completed the Sunbird-RC backend installation & frontend schema configuration but facing issues with the student registration form.

Open points:
  *  Currently, we have configured the specific schema JSON  (https://ndear.xiv.in/registry/api/docs/swagger.json). But can we use this schema for default use-case setup installation?
 * When using the above  JSON schema we are facing a CORS issue.
 * Proper key cloak configuration is required currently we are facing issues in URL redirection & configuration.
 * For backend installation- Suppose we shut down the Sunird-RC server, API's are not responding properly so we need to keep the server up & running state continuously or perform fresh backend installation after the start.

<b>please suggest </b>

**Comment by kesavanp123** [comment]
Hi Nagesh,

Q1. You need to set up the schema in your own server.
Q2. CORS happens, because, client and backend have different host names.
Are you sure the client and backend are having the same host name?
Q3. Can you please check the redirect / root urls of the client
registry-frontend in keycloak server, they have to be matched with the
frontend host url?
Q4. I am assuming you are restarting the box which means running docker
containers also will be stopped, in that case you need to install
everything from scratch. But to overcome this we can add restart policy in
docker-compose yml,
https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy
We
will add it soon.

**Reply by NageshRaykar** [reply]
@kesavanp123  
Please let me know a suitable time to have a quick call.

**Comment by kesavanp123** [comment]
Ok. Let's catch up around 2 PM.

**Comment by gamemaker1** [comment]
@NageshRaykar In case it helps, [here](https://github.com/Sunbird-RC/sunbird-rc-core/blob/main/docs/installation.md) is a quick installation and getting started guide for a minimal student-teacher registry using the Registry CLI.

**Reply by NageshRaykar** [reply]
@gamemaker1  
We have used the same link for quick installation.

**Reply by NageshRaykar** [reply]
@kesavanp123 
Currently, we are facing the below issue
1. Sunbird-RC Front-end portal is up but for Student/Teacher registration using portal we are getting status  200  in browser but getting response blank & User is not present in keycloak . Using the postman or curl command we are able to register Student/Teacher but the default password is not known so we need to reset the password in keycloak. where we can get the default password setting in the Sunbird RC configuration? 
2.  After login into the portal we are getting a CORS issue. Please refer to the below screenshot.

![image](https://user-images.githubusercontent.com/6999208/139379754-9a74b403-9770-4172-8bd7-e7fc4b3cd7bb.png)

Please Suggest.

**Reply by nsdlegovernancedevteam** [reply]
Hi @dileepbapat @kesavanp123 @coolbung @parthlawate,
cc: @NageshRaykar @NiranjanV12

The new Issue we are facing:

1) We are not able to do registration using front-end.
    In database there is entry in table `V_Student` for column `_osState/school` as `DRAFT`.
    This student user is not visible in keycloak.

db entry from `V_Student`
```
-[ RECORD 3 ]--------+-----------------------------------------
ID                   | 9
@type                | Student
osid                 | ec30f0f8-8c0c-4083-b4a0-92a9a99c0f70
above13              | Yes
identityDetails_osid | e93485c2-ca9d-481b-b218-375b13776f2f
contactDetails_osid  | 85ff344d-2b7e-4285-9863-a10298ba8b29
t&c                  | t
_osState/school      | DRAFT
name                 | 
phoneNumber          | 
email                | 
subject              | 
school               | 
```

2) We are able to register user by using post-man
But we are getting 401 unauthorised... the below error after login.
![IMG_20211101_151133](https://user-images.githubusercontent.com/75158135/139654117-5e1a611f-7f19-4a2b-9593-9243ddcbd69f.png)

Please suggest.

**Reply by gamemaker1** [reply]
Hi @nsdlegovernancedevteam @NageshRaykar @NiranjanV12,

It seems you are getting a invalid token issuer error. This is because the domain/IP address set in the issuer (`iss`) field in the JWTs returned by keycloak is different from the machine that is running keycloak. This usually happens when running keycloak using docker, or behind a proxy.

If you are using a docker compose file to start keycloak, you could add the following under the keycloak section: `KEYCLOAK_FRONTEND_URL=http://<ip address or domain>:8080/auth` as follows:

```yaml
kc:
  image: dockerhub/ndear-keycloak
  volumes:
    - ./imports:/opt/jboss/keycloak/imports
  environment:
    - DB_VENDOR=postgres
    - DB_ADDR=db
    - DB_PORT=5432
    - DB_DATABASE=registry
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
    - KEYCLOAK_FRONTEND_URL=http://xx.xx.xx.xx:8080/auth
  healthcheck:
    test: ['CMD-SHELL', 'curl -f http://localhost:9990/ || exit 1']
    interval: 30s
    timeout: 10s
    retries: 5
  ports:
    - '8080:8080'
    - '9990:9990'
```

This will ensure all JWTs created will be issued by that domain.

Please let me know if this solves your issue.
