### DISCUSSION TITLE
Facing issue in registering new entities

### DISCUSSION THREAD

**Discussion by radhay-samagra** [Sunbird-RC/community#219] [Issues] [answered]
I have been trying to register my schema on sunbird RC. I am able to see my schema getting registered at ```/api/docs/swagger.json``` but when I am making ```/invite``` API call for creating new entity I am getting error and found out below **_Exception_** in the logs: 
```Exception executing consequence for rule "Revert if any modification to ownership details" in dev.sunbirdrc.workflow: [Error: ruleEngineService.revertOwnershipDetails(stateDefinition): null]```

### Schema:
```
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"type": "object",
	"properties": {
		"state-hp": {
			"$ref": "#/definitions/state-hp"
		}
	},
	"required": ["state-hp"],
	"title": "state-hp",
	"definitions": {
		"state-hp": {
			"$id": "#/properties/state-hp",
			"type": "object",
			"title": "state-hp schema",
			"required": ["name"],
			"uniqueIndexFields": ["name"],
			"properties": {
				"name": {"type": "string"}
			}
		}
	},
	"_osConfig": {
		"ownershipAttributes": [
			{
				"userId": "/name"
			}
		],
		"inviteRoles": ["anonymous"],
		"enableLogin": true
	}
}
```

### docker-compose file: 
```
version: "2.4"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 4
  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  registry:
    image: dockerhub/sunbird-rc-core:v0.0.5
    environment:
      - authentication_enabled=true
      - signature_enabled=false
      - connectionInfo_uri=jdbc:postgresql://db:5432/registry
      - connectionInfo_username=postgres
      - connectionInfo_password=postgres
      - elastic_search_connection_url=es:9200
      - search_provider=dev.sunbirdrc.registry.service.ElasticSearchService
      - sunbird_sso_realm=sunbird-rc
      - sunbird_sso_url=http://keycloak:8080/auth
      - sunbird_sso_admin_client_id=admin-api
      - sunbird_sso_admin_client_secret=d112548e-09b8-411d-a1e0-b5870247affa
      - sunbird_sso_client_id=registry-frontend
      - claims_url=http://claim-ms:8082
      - sunbird_keycloak_user_set_password=true
      - sunbird_keycloak_user_password=abcd@123
      - filestorage_connection_url=http://file-storage:9000
      - filestorage_access_key=admin
      - filestorage_secret_key=ced9862ea6
      - filestorage_bucket_key=ndear
      - external_entities=board-cbse
    ports:
      - "8081:8081"
    volumes: 
      - ./schemas:/home/sunbirdrc/config/public/_schemas
    depends_on:
      es:
        condition: service_healthy
      db:
        condition: service_started
  keycloak:
    image: dockerhub/ndear-keycloak
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_PORT=5432
      - DB_DATABASE=registry
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
      - PROXY_ADDRESS_FORWARDING=true
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9990/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      db:
        condition: service_started
  claim-ms:
    image: dockerhub/sunbird-rc-claim-ms:v0.0.5
    environment:
      - connectionInfo_uri=jdbc:postgresql://db:5432/registry
      - connectionInfo_username=postgres
      - connectionInfo_password=postgres
      - sunbirdrc_url=http://registry:8081
      - logging.level.root=DEBUG
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_started
      registry:
        condition: service_started
  file-storage:
    image: quay.io/minio/minio
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=ced9862ea6
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
```

### Reproduce:
> When using POST ```/api/v1/state-hp/invite``` API request with body 
```
{
"name": "Test school"
}
```

I got following error:
```
{
    "id": "sunbird-rc.registry.invite",
    "ver": "1.0",
    "ets": 1651053528580,
    "params": {
        "resmsgid": "",
        "msgid": "fe6a78ee-e8eb-4bdb-9427-f1889d399411",
        "err": "",
        "status": "UNSUCCESSFUL",
        "errmsg": "Error occurred"
    },
    "responseCode": "OK"
}
```
 and respective logs:
```
registry_1      | 09:58:48.733 [http-nio-8081-exec-2] ERROR dev.sunbirdrc.pojos.RequestWrapper:39 - Can't read from http stream. Set body empty
registry_1      | 09:58:48.741 [http-nio-8081-exec-2] ERROR dev.sunbirdrc.pojos.APIMessage:44 - Can't read request body
registry_1      | 09:58:48.808 [http-nio-8081-exec-2] INFO  d.s.r.helper.EntityStateHelper:65 - Detecting state changes by comparing attestation paths in existing and the updated nodes
registry_1      | 09:58:49.107 [http-nio-8081-exec-2] INFO  d.s.r.controller.AbstractController:56 - Error in handling the invite
registry_1      | org.kie.api.runtime.rule.ConsequenceException: Exception executing consequence for rule "Revert if any modification to ownership details" in dev.sunbirdrc.workflow: [Error: ruleEngineService.revertOwnershipDetails(stateDefinition): null]
registry_1      | [Near : {... ruleEngineService.revertOwners ....}]
```

Can you help me where I am going wrong here. As I am creating a new entity from scratch with no attestation policies.
