### DISCUSSION TITLE
Audit is not generating

### DISCUSSION THREAD

**Discussion by shiva-rakshith** [Sunbird-RC/community#350] [Issues]
We have enabled audit generation in registry and using elastic search as audit store. But audit is not generating.

We are using the below configuration:
```
audit:
  enabled: ${audit_enabled:true}
  frame:
    store: ${audit_frame_store:ELASTIC}
    suffix: ${audit_suffix:registry_audit}
    suffixSeparator: ${auditsuffixSeparator:_}
```

Do we need to make any other configuration to enable audit?
